#!/bin/sh
#
#    dataman-header - welcome message
#    Copyright (C) 2015-2021 DataMan Inc.
#
#    Authors: weitao zhou <wtzhou@dataman-inc.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.

# ███████╗██╗  ██╗██╗   ██╗    ██████╗ ███████╗███╗   ██╗    ██╗   ██╗██╗   ██╗███╗   ██╗
# ██╔════╝██║  ██║██║   ██║    ██╔══██╗██╔════╝████╗  ██║    ╚██╗ ██╔╝██║   ██║████╗  ██║
# ███████╗███████║██║   ██║    ██████╔╝█████╗  ██╔██╗ ██║     ╚████╔╝ ██║   ██║██╔██╗ ██║
# ╚════██║██╔══██║██║   ██║    ██╔══██╗██╔══╝  ██║╚██╗██║      ╚██╔╝  ██║   ██║██║╚██╗██║
# ███████║██║  ██║╚██████╔╝    ██║  ██║███████╗██║ ╚████║       ██║   ╚██████╔╝██║ ╚████║
# ╚══════╝╚═╝  ╚═╝ ╚═════╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝       ╚═╝    ╚═════╝ ╚═╝  ╚═══╝  @DataMan Inc.

cat /usr/lib/dataman/shurenyun-logo.ansi-art
